# netlify.toml — site estático
[build]
  publish = "."   # publica a pasta raiz (onde está o index.html)

# Opcional: cache básico para ativos
[[headers]]
  for = "/**"
  [headers.values]
    cache-control = "public, max-age=600"
