# netlify.toml — configuração para site estático
[build]
  # Não há comando de build, apenas publicar os arquivos da raiz
  publish = "."

# Se quiser garantir que todas as rotas levem para index.html
# (útil caso você adicione SPA futuramente)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache básico para arquivos estáticos
[[headers]]
  for = "/**"
  [headers.values]
    cache-control = "public, max-age=600"
